# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: k6 with ci/cd

on: 
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      working-directory: ./k6/services/userSubscription
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      run: | 
        npm ci
        npm run build --if-present
    
    - name: Run k6 local test
      uses: grafana/k6-action@v0.2.0
      with:
        filename: /k6/tests/k6.js
        flags: --vus 10 --duration 20s --env testType=smoke
        cloud: true
        token: ${{ secrets.K6_CLOUD_API_TOKEN }}
     
  
